DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  board_id INT NOT NULL,
  comment_no SMALLINT NOT NULL,
  comment_body VARCHAR(1000) NOT NULL,
  status TINYINT(5) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
  FOREIGN KEY (board_id) REFERENCES BOARDS(id) ON DELETE CASCADE
);