DROP TABLE IF EXISTS COMMENT_REPLIES;
CREATE TABLE COMMENT_REPLIES (
  id INT PRIMARY KEY AUTO_INCREMENT,
  t_comment_to_id INT,
  t_comment_from_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (t_comment_to_id) REFERENCES COMMENTS(id) ON DELETE SET NULL,
  FOREIGN KEY (t_comment_from_id) REFERENCES COMMENTS(id) ON DELETE CASCADE
);