DROP TABLE IF EXISTS COMMENT_FILES;
CREATE TABLE COMMENT_FILES (
  id INT PRIMARY KEY AUTO_INCREMENT,
  comment_id INT,
  file_name VARCHAR(64) NOT NULL,
  status TINYINT(5) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (comment_id) REFERENCES COMMENTS(id) ON DELETE SET NULL
);