DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(254) UNIQUE NOT NULL, 
  password VARCHAR(255) NOT NULL,
  status TINYINT(5) DEFAULT 0,
  login_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);