DROP TABLE IF EXISTS BOARDS;
CREATE TABLE BOARDS (id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(500),
  status TINYINT(3) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE SET NULL
);